services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StudioMitte\LiveSearchExtended\:
    resource: '../Classes/*'
    exclude: '../Classes/Provider/FormDataProvider.php'

  StudioMitte\LiveSearchExtended\EventListener\ModifyResultEventListener:
    tags:
      - name: event.listener
        identifier: 'live-search-extended-modify-resultitem'
        event: TYPO3\CMS\Backend\Search\Event\ModifyResultItemInLiveSearchEvent

  StudioMitte\LiveSearchExtended\EventListener\RowModification\SysTemplateRowModificationEventListener:
    tags:
      - name: event.listener
        identifier: 'live-search-extended-modify-systemplate'
        event: StudioMitte\LiveSearchExtended\Event\ModifyRowEvent