services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StudioMitte\LiveSearchExtended\:
    resource: '../Classes/*'

  StudioMitte\LiveSearchExtended\EventListener\ModifyResultEventListener:
    tags:
      - name: event.listener
        identifier: 'live-search-extended-modfy-resultitem'
        event: TYPO3\CMS\Backend\Search\Event\ModifyResultItemInLiveSearchEvent